const emojipedia = [
  { id: 1, emoji: "💪", name: "Tense Biceps", meaning: "You can do that! or I feel strong! Arm with tense biceps. Also used in connection with doing sports, e.g. at the gym." },
  { id: 2, emoji: "🙏", name: "Person With Folded Hands", meaning: "Two hands pressed together. Used for prayer, gratitude, or a high five." },
  { id: 3, emoji: "🤣", name: "Rolling On The Floor, Laughing", meaning: "A smiley face, rolling on the floor, laughing uncontrollably." },
  { id: 4, emoji: "😎", name: "Smiling Face With Sunglasses", meaning: "Cool, relaxed, or confident attitude." },
  { id: 5, emoji: "😇", name: "Smiling Face With Halo", meaning: "Represents innocence, kindness, or holiness." },
  { id: 6, emoji: "🤔", name: "Thinking Face", meaning: "Used to indicate thinking, curiosity, or doubt." },
  { id: 7, emoji: "😍", name: "Smiling Face With Heart-Eyes", meaning: "Expresses love, admiration, or enthusiasm." },
  { id: 8, emoji: "😢", name: "Crying Face", meaning: "Represents sadness, pain, or disappointment." },
  { id: 9, emoji: "😡", name: "Pouting Face", meaning: "Used to show anger or frustration." },
  { id: 10, emoji: "🤯", name: "Exploding Head", meaning: "Represents shock, amazement, or a mind-blowing realization." },
  { id: 11, emoji: "🤗", name: "Hugging Face", meaning: "A friendly smiley giving a hug." },
  { id: 12, emoji: "😴", name: "Sleeping Face", meaning: "Indicates sleepiness or boredom." },
  { id: 13, emoji: "😷", name: "Face With Medical Mask", meaning: "Represents illness or concern for hygiene." },
  { id: 14, emoji: "🤮", name: "Face Vomiting", meaning: "Used to show extreme disgust." },
  { id: 15, emoji: "💀", name: "Skull", meaning: "Represents death, danger, or something extremely funny." },
  { id: 16, emoji: "🎉", name: "Party Popper", meaning: "Used for celebrations and special occasions." },
  { id: 17, emoji: "🔥", name: "Fire", meaning: "Represents something hot, cool, or trending." },
  { id: 18, emoji: "💯", name: "Hundred Points", meaning: "Indicates something is 100% or perfect." },
  { id: 19, emoji: "🚀", name: "Rocket", meaning: "Symbolizes fast progress or a big launch." },
  { id: 20, emoji: "🎯", name: "Bullseye", meaning: "Represents precision or achieving a goal." },
  { id: 21, emoji: "🤩", name: "Star-Struck", meaning: "Shows amazement or admiration." },
  { id: 22, emoji: "🙄", name: "Face With Rolling Eyes", meaning: "Expresses sarcasm or annoyance." },
  { id: 23, emoji: "🥶", name: "Cold Face", meaning: "Indicates extreme cold or shock." },
  { id: 24, emoji: "🤡", name: "Clown Face", meaning: "Used to represent foolishness or clownish behavior." },
  { id: 25, emoji: "👀", name: "Eyes", meaning: "Used to indicate looking, interest, or suspicion." },
  { id: 26, emoji: "💡", name: "Light Bulb", meaning: "Represents an idea or inspiration." },
  { id: 27, emoji: "🎵", name: "Musical Note", meaning: "Used for music, rhythm, or sound." },
  { id: 28, emoji: "🍕", name: "Pizza", meaning: "Represents food, cravings, or Italian cuisine." },
  { id: 29, emoji: "☕", name: "Hot Beverage", meaning: "Symbolizes coffee, tea, or warmth." },
  { id: 30, emoji: "🏆", name: "Trophy", meaning: "Represents victory, achievement, or success." },
  { id: 31, emoji: "📅", name: "Calendar", meaning: "Indicates scheduling or an important date." },
  { id: 32, emoji: "📌", name: "Pushpin", meaning: "Used for marking something important." },
  { id: 33, emoji: "🔒", name: "Locked", meaning: "Represents security, privacy, or confidentiality." },
  { id: 34, emoji: "❤️", name: "Red Heart", meaning: "Expresses love, passion, or deep affection." },
  { id: 35, emoji: "💔", name: "Broken Heart", meaning: "Represents heartbreak or emotional pain." },
  { id: 36, emoji: "🐶", name: "Dog Face", meaning: "Represents a pet dog or cuteness." },
  { id: 37, emoji: "🐱", name: "Cat Face", meaning: "Represents a pet cat or playfulness." },
  { id: 38, emoji: "🦊", name: "Fox Face", meaning: "Represents cleverness, cunning, or playfulness." },
  { id: 39, emoji: "🐻", name: "Bear Face", meaning: "Symbolizes warmth, protection, or wildness." },
  { id: 40, emoji: "🐼", name: "Panda Face", meaning: "Represents cuteness, gentleness, or laziness." },
  { id: 41, emoji: "🌍", name: "Globe Showing Europe-Africa", meaning: "Represents the world, earth, or environment." },
  { id: 42, emoji: "🌞", name: "Sun With Face", meaning: "Represents warmth, happiness, or a bright day." },
  { id: 43, emoji: "🌙", name: "Crescent Moon", meaning: "Symbolizes nighttime, rest, or dreams." },
  { id: 44, emoji: "⭐", name: "Star", meaning: "Represents excellence, brightness, or space." },
  { id: 45, emoji: "☂️", name: "Umbrella", meaning: "Represents rain, protection, or travel." },
  { id: 46, emoji: "🐸", name: "Frog Face", meaning: "Represents frogs, nature, or a calm attitude." },
  { id: 47, emoji: "🐢", name: "Turtle", meaning: "Symbolizes slowness, patience, or wisdom." },
  { id: 48, emoji: "🐍", name: "Snake", meaning: "Represents danger, cunning, or transformation." },
  { id: 49, emoji: "🐙", name: "Octopus", meaning: "Symbolizes intelligence, flexibility, or the ocean." },
  { id: 50, emoji: "🦑", name: "Squid", meaning: "Used for marine life, adaptability, or mystery." },
  { id: 51, emoji: "🦞", name: "Lobster", meaning: "Represents seafood, strength, or resilience." },
  { id: 52, emoji: "🦜", name: "Parrot", meaning: "Symbolizes talkativeness, intelligence, or tropical vibes." },
  { id: 53, emoji: "🦩", name: "Flamingo", meaning: "Used for elegance, uniqueness, or exotic places." },
  { id: 54, emoji: "🦔", name: "Hedgehog", meaning: "Represents cuteness, protection, or introversion." },
  { id: 55, emoji: "🐿️", name: "Chipmunk", meaning: "Symbolizes playfulness, energy, or hoarding." },
  { id: 56, emoji: "🦦", name: "Otter", meaning: "Used for fun, teamwork, or aquatic life." },
  { id: 57, emoji: "🐋", name: "Whale", meaning: "Represents wisdom, depth, or marine conservation." },
  { id: 58, emoji: "🐬", name: "Dolphin", meaning: "Symbolizes intelligence, playfulness, or the ocean." },
  { id: 59, emoji: "🐠", name: "Tropical Fish", meaning: "Represents exotic fish, aquariums, or the sea." },
  { id: 60, emoji: "🦈", name: "Shark", meaning: "Used for fear, power, or oceanic themes." },
  { id: 61, emoji: "🦓", name: "Zebra", meaning: "Symbolizes uniqueness, adventure, or safari life." },
  { id: 62, emoji: "🦒", name: "Giraffe", meaning: "Represents curiosity, height, or Africa." },
  { id: 63, emoji: "🦘", name: "Kangaroo", meaning: "Used for Australia, energy, or jumping." },
  { id: 64, emoji: "🐉", name: "Dragon", meaning: "Represents power, mythology, or fantasy stories." },
  { id: 65, emoji: "🐲", name: "Dragon Face", meaning: "Symbolizes strength, wisdom, or Eastern cultures." },
  { id: 66, emoji: "🦚", name: "Peacock", meaning: "Used for beauty, pride, or elegance." },
  { id: 67, emoji: "🦢", name: "Swan", meaning: "Represents grace, transformation, or love." },
  { id: 68, emoji: "🐦", name: "Bird", meaning: "Symbolizes freedom, nature, or songbirds." },
  { id: 69, emoji: "🦉", name: "Owl", meaning: "Represents wisdom, night, or mystery." },
  { id: 70, emoji: "🦜", name: "Parrot", meaning: "Used for mimicry, intelligence, or pirates." },
  { id: 71, emoji: "🐕", name: "Dog", meaning: "Represents loyalty, pets, or companionship." },
  { id: 72, emoji: "🐈", name: "Cat", meaning: "Symbolizes independence, mystery, or playfulness." },
  { id: 73, emoji: "🐎", name: "Horse", meaning: "Used for speed, strength, or horse riding." },
  { id: 74, emoji: "🦄", name: "Unicorn", meaning: "Represents fantasy, magic, or uniqueness." },
  { id: 75, emoji: "🐄", name: "Cow", meaning: "Symbolizes farming, dairy, or Hindu culture." },
  { id: 76, emoji: "🐖", name: "Pig", meaning: "Represents farm animals, pork, or wealth in some cultures." },
  { id: 77, emoji: "🦌", name: "Deer", meaning: "Symbolizes grace, nature, or Christmas themes." },
  { id: 78, emoji: "🦇", name: "Bat", meaning: "Used for Halloween, night, or the supernatural." },
  { id: 79, emoji: "🦅", name: "Eagle", meaning: "Represents freedom, strength, or the USA." },
  { id: 80, emoji: "🐝", name: "Bee", meaning: "Symbolizes hard work, nature, or sweetness." },
  { id: 81, emoji: "🦋", name: "Butterfly", meaning: "Used for transformation, beauty, or nature." },
  { id: 82, emoji: "🐞", name: "Ladybug", meaning: "Represents good luck, gardens, or insects." },
  { id: 83, emoji: "🦂", name: "Scorpion", meaning: "Used for danger, mystery, or Scorpio zodiac sign." },
  { id: 84, emoji: "🐛", name: "Bug", meaning: "Represents insects, nature, or transformation." },
  { id: 85, emoji: "🦠", name: "Microbe", meaning: "Symbolizes germs, science, or viruses." },
  { id: 86, emoji: "🍄", name: "Mushroom", meaning: "Represents nature, fantasy, or food." },
  { id: 87, emoji: "🌵", name: "Cactus", meaning: "Symbolizes desert life, resilience, or nature." },
  { id: 88, emoji: "🎄", name: "Christmas Tree", meaning: "Used for holidays, joy, or winter themes." },
  { id: 89, emoji: "🌞", name: "Sun With Face", meaning: "Represents warmth, positivity, or the sky." },
  { id: 90, emoji: "🌛", name: "Crescent Moon Face", meaning: "Symbolizes nighttime, dreams, or relaxation." },
  { id: 91, emoji: "🌈", name: "Rainbow", meaning: "Used for positivity, pride, or weather themes." },
  { id: 92, emoji: "❄️", name: "Snowflake", meaning: "Represents winter, cold, or uniqueness." },
  { id: 93, emoji: "🔥", name: "Fire", meaning: "Used for energy, heat, or something amazing." },
  { id: 94, emoji: "💧", name: "Droplet", meaning: "Symbolizes water, tears, or rain." },
  { id: 95, emoji: "🌊", name: "Ocean Wave", meaning: "Used for beach, surfing, or water themes." },
  { id: 96, emoji: "🌪️", name: "Tornado", meaning: "Represents storms, chaos, or strong winds." },
  { id: 97, emoji: "🌠", name: "Shooting Star", meaning: "Symbolizes wishes, space, or good luck." },
  { id: 98, emoji: "🪐", name: "Ringed Planet", meaning: "Used for space, astronomy, or Saturn." },
  { id: 99, emoji: "💫", name: "Dizzy", meaning: "Represents spinning, stars, or being lightheaded." },
  { id: 100, emoji: "☄️", name: "Comet", meaning: "Symbolizes space, rarity, or astronomical events." },
  { id: 101, emoji: "🥺", name: "Pleading Face", meaning: "A cute, begging expression often used to show puppy-dog eyes." },
  { id: 102, emoji: "🤤", name: "Drooling Face", meaning: "Represents hunger, desire, or attraction to something delicious or appealing." },
  { id: 103, emoji: "😵", name: "Dizzy Face", meaning: "A dazed, spiraling-eye expression showing confusion, exhaustion, or shock." },
  { id: 104, emoji: "🥱", name: "Yawning Face", meaning: "Expresses tiredness, boredom, or needing rest." },
  { id: 105, emoji: "😈", name: "Smiling Face With Horns", meaning: "A mischievous smiley, representing playful trouble or naughtiness." },
  { id: 106, emoji: "👹", name: "Ogre", meaning: "A mythological monster used to express something scary or evil." },
  { id: 107, emoji: "🤠", name: "Cowboy Hat Face", meaning: "Represents adventure, the Wild West, or a carefree attitude." },
  { id: 108, emoji: "🥷", name: "Ninja", meaning: "Symbolizes stealth, secrecy, or an agile personality." },
  { id: 109, emoji: "🤖", name: "Robot", meaning: "Represents technology, AI, or something robotic." },
  { id: 110, emoji: "🎭", name: "Performing Arts", meaning: "Symbolizes theater, drama, or entertainment." },
  { id: 111, emoji: "🕵️", name: "Detective", meaning: "Represents investigation, mystery, or secrecy." },
  { id: 112, emoji: "👩‍🚀", name: "Astronaut", meaning: "Represents space exploration, ambition, or dreaming big." },
  { id: 113, emoji: "🦸", name: "Superhero", meaning: "Symbolizes heroism, bravery, or someone admired." },
  { id: 114, emoji: "🦹", name: "Supervillain", meaning: "Represents an antagonist or someone with cunning plans." },
  { id: 115, emoji: "🧙", name: "Mage", meaning: "Symbolizes magic, spells, or wisdom." },
  { id: 116, emoji: "🧚", name: "Fairy", meaning: "Represents fantasy, wonder, or innocence." },
  { id: 117, emoji: "🧛", name: "Vampire", meaning: "Symbolizes gothic themes, mystery, or immortality." },
  { id: 118, emoji: "🧜", name: "Mermaid", meaning: "Represents the ocean, myths, or fantasy worlds." },
  { id: 119, emoji: "🐉", name: "Dragon", meaning: "Symbolizes power, mythology, or fantasy." },
  { id: 120, emoji: "🦄", name: "Unicorn", meaning: "Represents uniqueness, magic, or wonder." },
  { id: 121, emoji: "🎃", name: "Jack-O-Lantern", meaning: "Represents Halloween, spookiness, or fun decorations." },
  { id: 122, emoji: "🕷️", name: "Spider", meaning: "Symbolizes creepiness, Halloween, or being crafty." },
  { id: 123, emoji: "🦇", name: "Bat", meaning: "Represents the night, mystery, or Halloween themes." },
  { id: 124, emoji: "🪄", name: "Magic Wand", meaning: "Symbolizes magic, fantasy, or transformation." },
  { id: 125, emoji: "📖", name: "Open Book", meaning: "Represents learning, storytelling, or knowledge." },
  { id: 126, emoji: "📝", name: "Memo", meaning: "Symbolizes writing, notes, or making lists." },
  { id: 127, emoji: "🖊️", name: "Pen", meaning: "Represents writing, creativity, or signing something important." },
  { id: 128, emoji: "🖥️", name: "Desktop Computer", meaning: "Symbolizes technology, work, or digital space." },
  { id: 129, emoji: "💾", name: "Floppy Disk", meaning: "A retro symbol for saving data or old-school technology." },
  { id: 130, emoji: "📡", name: "Satellite Antenna", meaning: "Represents communication, broadcasting, or technology." },
  { id: 131, emoji: "🎧", name: "Headphones", meaning: "Symbolizes music, listening, or focus." },
  { id: 132, emoji: "📺", name: "Television", meaning: "Represents entertainment, media, or watching shows." },
  { id: 133, emoji: "📻", name: "Radio", meaning: "Represents news, music, or traditional broadcasting." },
  { id: 134, emoji: "📷", name: "Camera", meaning: "Symbolizes photography, capturing memories, or taking pictures." },
  { id: 135, emoji: "🕰️", name: "Mantelpiece Clock", meaning: "Represents time, punctuality, or nostalgia for classic designs." },
  { id: 136, emoji: "⏳", name: "Hourglass", meaning: "Symbolizes time running out, patience, or waiting for something important." },
  { id: 137, emoji: "⚖️", name: "Balance Scale", meaning: "Represents fairness, justice, or weighing different options." },
  { id: 138, emoji: "🔮", name: "Crystal Ball", meaning: "Symbolizes fortune-telling, mysticism, or future predictions." },
  { id: 139, emoji: "💎", name: "Gem Stone", meaning: "Represents luxury, wealth, or something precious and valuable." },
  { id: 140, emoji: "🛡️", name: "Shield", meaning: "Symbolizes protection, security, or strength." },
  { id: 141, emoji: "⚔️", name: "Crossed Swords", meaning: "Represents battle, competition, or historical warfare." },
  { id: 142, emoji: "🚀", name: "Rocket", meaning: "Symbolizes rapid growth, ambition, or space exploration." },
  { id: 143, emoji: "🛸", name: "Flying Saucer", meaning: "Represents UFOs, aliens, or extraterrestrial life." },
  { id: 144, emoji: "🌍", name: "Earth Globe", meaning: "Symbolizes global awareness, travel, or environmental consciousness." },
  { id: 145, emoji: "🪐", name: "Ringed Planet", meaning: "Represents astronomy, outer space, or planets like Saturn." },
  { id: 146, emoji: "☀️", name: "Sun", meaning: "Symbolizes warmth, happiness, or sunny weather." },
  { id: 147, emoji: "🌕", name: "Full Moon", meaning: "Represents nighttime, lunar cycles, or supernatural themes." },
  { id: 148, emoji: "🌓", name: "First Quarter Moon", meaning: "Symbolizes transition, phases of life, or change." },
  { id: 149, emoji: "🌧️", name: "Cloud With Rain", meaning: "Represents rainy weather, sadness, or melancholy moods." },
  { id: 150, emoji: "🌪️", name: "Tornado", meaning: "Symbolizes chaos, destruction, or turbulent emotions." },
  { id: 151, emoji: "🌈", name: "Rainbow", meaning: "Represents hope, diversity, and positivity." },
  { id: 152, emoji: "🔥", name: "Fire", meaning: "Symbolizes heat, energy, passion, or something trending." },
  { id: 153, emoji: "💧", name: "Droplet", meaning: "Represents water, hydration, or emotions like crying." },
  { id: 154, emoji: "🌊", name: "Ocean Wave", meaning: "Symbolizes nature, surfing, or going with the flow." },
  { id: 155, emoji: "🪵", name: "Wood Log", meaning: "Represents nature, camping, or fuel for a fire." },
  { id: 156, emoji: "🏔️", name: "Snow-Capped Mountain", meaning: "Symbolizes adventure, hiking, or cold destinations." },
  { id: 157, emoji: "🏕️", name: "Camping", meaning: "Represents outdoor activities, nature, or vacations." },
  { id: 158, emoji: "🏠", name: "House", meaning: "Symbolizes home, family, or real estate." },
  { id: 159, emoji: "🏢", name: "Office Building", meaning: "Represents business, workplaces, or urban environments." },
  { id: 160, emoji: "🏛️", name: "Classical Building", meaning: "Symbolizes government, history, or education institutions." },
  { id: 161, emoji: "🗼", name: "Tokyo Tower", meaning: "Represents Japan, travel, or sightseeing." },
  { id: 162, emoji: "🗽", name: "Statue of Liberty", meaning: "Symbolizes freedom, New York, or the United States." },
  { id: 163, emoji: "🕌", name: "Mosque", meaning: "Represents Islamic faith, worship, or Middle Eastern culture." },
  { id: 164, emoji: "⛩️", name: "Shinto Shrine", meaning: "Symbolizes Japanese culture, tradition, or religious sites." },
  { id: 165, emoji: "🚂", name: "Steam Locomotive", meaning: "Represents train travel, history, or transportation." },
  { id: 166, emoji: "🚗", name: "Car", meaning: "Symbolizes travel, road trips, or driving." },
  { id: 167, emoji: "🚲", name: "Bicycle", meaning: "Represents eco-friendly transport, fitness, or commuting." },
  { id: 168, emoji: "🚁", name: "Helicopter", meaning: "Symbolizes fast travel, military, or emergency services." },
  { id: 169, emoji: "🛳️", name: "Cruise Ship", meaning: "Represents luxury travel, vacations, or sea adventures." },
  { id: 170, emoji: "⛵", name: "Sailboat", meaning: "Symbolizes leisure, adventure, or the ocean." },
  { id: 171, emoji: "🛶", name: "Canoe", meaning: "Represents outdoor sports, nature, or water activities." },
  { id: 172, emoji: "✈️", name: "Airplane", meaning: "Symbolizes travel, vacations, or flight experiences." },
  { id: 173, emoji: "🪂", name: "Parachute", meaning: "Represents adventure sports, skydiving, or safety." },
  { id: 174, emoji: "🚦", name: "Traffic Light", meaning: "Symbolizes road safety, rules, or waiting times." },
  { id: 175, emoji: "⚓", name: "Anchor", meaning: "Represents stability, strength, or maritime themes." },
  { id: 176, emoji: "🎸", name: "Guitar", meaning: "Symbolizes music, concerts, or rock culture." },
  { id: 177, emoji: "🎷", name: "Saxophone", meaning: "Represents jazz, smooth music, or playing an instrument." },
  { id: 178, emoji: "🥁", name: "Drum", meaning: "Symbolizes rhythm, music, or making noise." },
  { id: 179, emoji: "🎤", name: "Microphone", meaning: "Represents singing, performance, or public speaking." },
  { id: 180, emoji: "🎼", name: "Musical Score", meaning: "Symbolizes classical music, composing, or reading music." },
  { id: 181, emoji: "📚", name: "Books", meaning: "Represents studying, knowledge, or literature." },
  { id: 182, emoji: "🧵", name: "Thread", meaning: "Symbolizes sewing, creativity, or patience." },
  { id: 183, emoji: "🪡", name: "Sewing Needle", meaning: "Represents stitching, repairs, or crafting." },
  { id: 184, emoji: "🧶", name: "Yarn", meaning: "Symbolizes knitting, crocheting, or warmth." },
  { id: 185, emoji: "🛒", name: "Shopping Cart", meaning: "Represents grocery shopping, retail, or e-commerce." },
  { id: 186, emoji: "🎁", name: "Wrapped Gift", meaning: "Symbolizes presents, surprises, or celebrations." },
  { id: 187, emoji: "🎀", name: "Ribbon", meaning: "Represents gifts, decoration, or beauty." },
  { id: 188, emoji: "🏅", name: "Sports Medal", meaning: "Symbolizes achievement, victory, or excellence in sports." },
  { id: 189, emoji: "🎖️", name: "Military Medal", meaning: "Represents honor, bravery, or military service." },
  { id: 190, emoji: "🏆", name: "Trophy", meaning: "Symbolizes success, championship, or accomplishment." },
  { id: 191, emoji: "🥇", name: "1st Place Medal", meaning: "Represents being the best, winning, or excelling in a competition." },
  { id: 192, emoji: "🥈", name: "2nd Place Medal", meaning: "Symbolizes second place, silver medalist, or honorable achievement." },
  { id: 193, emoji: "🥉", name: "3rd Place Medal", meaning: "Represents third place, bronze medalist, or a respectable win." },
  { id: 194, emoji: "⚽", name: "Soccer Ball", meaning: "Symbolizes football, sports, or playing a match." },
  { id: 195, emoji: "🏀", name: "Basketball", meaning: "Represents basketball, shooting hoops, or sports competitions." },
  { id: 196, emoji: "🎾", name: "Tennis Ball", meaning: "Symbolizes tennis, matches, or athletic competition." },
  { id: 197, emoji: "🎳", name: "Bowling", meaning: "Represents bowling sports, leisure activities, or strikes." },
  { id: 198, emoji: "🛹", name: "Skateboard", meaning: "Symbolizes skateboarding, extreme sports, or urban culture." },
  { id: 199, emoji: "🚴", name: "Bicyclist", meaning: "Represents cycling, fitness, or eco-friendly transport." },
  { id: 200, emoji: "🏄", name: "Surfer", meaning: "Symbolizes surfing, beach life, or riding the waves." }
];



export default emojipedia;